### PR TITLE
Update For Zram Resizeing 

### PR DESCRIPTION
**Pull request by Yazed-Hasan**

### CODE REVIEW

**Review by Yazed-Hasan — COMMENTED** [review]
Test This Bro

**Comment by lululoid** [comment]
Making swap in boot seems like a good idea for user experience, but when it comes to opt for not activating psi tweak, it's just weird. This module is psi activator it's weird if it doesn't apply it.

The next thing is resizing zram to half of its memory. You should read [this](https://unix.stackexchange.com/questions/594817/why-does-zram-occupy-much-more-memory-compared-to-its-compressed-value) For my reason, in practice it could be more, but I hit high IO when setting it to 150% RAM size.

**Comment by Yazed20** [comment]
good job 👍 bro im still new in shell development 
 : ) 

lets see what else can optimize

**Comment by lululoid** [comment]
I can't merge this, there's issue in service.sh and somethings else, I followed your code tidy style though, I think it's good practice especially when your skill grow

**Pull request closed without merging**
